### ISSUE TITLE
请问为何路由部分的懒加载没法使用？

### ISSUE THREAD

**Issue by seymour8023** [xusenlin/ElementUIAdmin2#3]
路由懒加载写法：
  component: resolve => require(['@/views/home/Index.vue'], resolve),
  ...
  打开首页就会把所有js都加载出来

**Comment by xusenlin** [comment]
你好，我下班查看之后给你回复。：） 在2019年02月15日 11:27 ，seymour写道： Closed #3. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by xusenlin** [comment]
很抱歉现在才回复你，已经解决 。https://cli.vuejs.org/guide/html-and-static-assets.html#preload    预取
<link rel="prefetch"> 是一种资源提示，告诉浏览器在页面加载完成后，在浏览器的空闲时间内预取用户可能在不久的将来访问的内容。

默认情况下，Vue CLI应用程序将自动为为异步块生成的所有JavaScript文件生成预取提示

**Comment by seymour8023** [comment]
谢谢，

后来我也查到是preload的作用了，还是非常感谢能够回复！



gxy8023@163.com
 
发件人： 徐森林
发送时间： 2019-03-18 21:33
收件人： xusenlin/ElementUIAdmin2
抄送： seymour; State change
主题： Re: [xusenlin/ElementUIAdmin2] 请问为何路由部分的懒加载没法使用？ (#3)
很抱歉现在才回复你，已经解决 。https://cli.vuejs.org/guide/html-and-static-assets.html#preload 预取
是一种资源提示，告诉浏览器在页面加载完成后，在浏览器的空闲时间内预取用户可能在不久的将来访问的内容。 
默认情况下，Vue CLI应用程序将自动为为异步块生成的所有JavaScript文件生成预取提示
