### ISSUE TITLE
self.$Api.departDelete中的self.$Api以及departDelete在哪里定义的？

### ISSUE THREAD

**Issue by BillowsVan** [xusenlin/ElementUIAdmin2#4]
首先非常感谢作者
使用过程中有一个疑问
比如 src/views/categoryManage/Index.vue中
self.$Api.departDelete({id:id},r=>{....
这个 self.$Api以及departDelete在哪里定义的？
能不能提供一个对应的后台的模板？

**Comment by xusenlin** [comment]
感谢你的使用，这种做法是之前通过Vue.prototype.$Api = Api 将所有请求挂载到vue原型上，避免使用请求的时候需要导入函数，现在已经不再推荐这种做法了，目前只有配置才会挂载。departDelete是一个api请求函数，你可以自己在api文件夹定义然后导入到你需要使用的地方 :)
